import frappe

def create_phase4_doctypes():
    frappe.init(site="applicant-processing.localhost")
    frappe.connect()
    
    # Data Request Type
    if not frappe.db.exists("DocType", "Data Request Type"):
        doc_type = frappe.get_doc({
            "doctype": "DocType",
            "name": "Data Request Type",
            "module": "Applicant Processing",
            "custom": 0,
            "naming_rule": "By fieldname",
            "autoname": "field:data_request_name",
            "fields": [
                {"fieldname": "data_request_name", "label": "Name", "fieldtype": "Data", "reqd": 1, "unique": 1},
                {"fieldname": "description", "label": "Description", "fieldtype": "Small Text"},
                {"fieldname": "mandatory", "label": "Mandatory", "fieldtype": "Check", "default": "0"},
                {"fieldname": "applicable_stage", "label": "Applicable Stage", "fieldtype": "Select", "options": "\nRegistration\nDocumentation\nContract\nVisa\nDeparture"}
            ],
            "permissions": [{"role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1}]
        })
        doc_type.insert(ignore_permissions=True)
        print("Created Data Request Type")
        
    # Data Request
    if not frappe.db.exists("DocType", "Data Request"):
        doc_req = frappe.get_doc({
            "doctype": "DocType",
            "name": "Data Request",
            "module": "Applicant Processing",
            "custom": 0,
            "naming_rule": "Expression",
            "autoname": "REQ-.#####",
            "fields": [
                {"fieldname": "applicant", "label": "Applicant", "fieldtype": "Link", "options": "Applicant", "reqd": 1},
                {"fieldname": "data_request_type", "label": "Data Request Type", "fieldtype": "Link", "options": "Data Request Type", "reqd": 1},
                {"fieldname": "description", "label": "Description", "fieldtype": "Small Text"},
                {"fieldname": "assigned_user", "label": "Assigned User", "fieldtype": "Link", "options": "User"},
                {"fieldname": "status", "label": "Status", "fieldtype": "Select", "options": "Pending\nIn Progress\nCompleted\nFailed", "default": "Pending"},
                {"fieldname": "completed_date", "label": "Completed Date", "fieldtype": "Datetime"}
            ],
            "permissions": [{"role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1}]
        })
        doc_req.insert(ignore_permissions=True)
        print("Created Data Request")

    # CV Record
    if not frappe.db.exists("DocType", "CV Record"):
        cv_rec = frappe.get_doc({
            "doctype": "DocType",
            "name": "CV Record",
            "module": "Applicant Processing",
            "custom": 0,
            "naming_rule": "Expression",
            "autoname": "CV-.#####",
            "fields": [
                {"fieldname": "applicant", "label": "Applicant", "fieldtype": "Link", "options": "Applicant", "reqd": 1},
                {"fieldname": "template", "label": "Template", "fieldtype": "Data"},
                {"fieldname": "generated_by", "label": "Generated By", "fieldtype": "Link", "options": "User"},
                {"fieldname": "generated_date", "label": "Generated Date", "fieldtype": "Datetime"},
                {"fieldname": "file_attachment", "label": "File Attachment", "fieldtype": "Attach"},
                {"fieldname": "version", "label": "Version", "fieldtype": "Int", "default": "1"},
                {"fieldname": "status", "label": "Status", "fieldtype": "Select", "options": "Draft\nFinal", "default": "Draft"}
            ],
            "permissions": [{"role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1}]
        })
        cv_rec.insert(ignore_permissions=True)
        print("Created CV Record")

    # Contractor
    if not frappe.db.exists("DocType", "Contractor"):
        contractor = frappe.get_doc({
            "doctype": "DocType",
            "name": "Contractor",
            "module": "Applicant Processing",
            "custom": 0,
            "naming_rule": "By fieldname",
            "autoname": "field:company_name",
            "fields": [
                {"fieldname": "company_name", "label": "Company Name", "fieldtype": "Data", "reqd": 1, "unique": 1},
                {"fieldname": "contact_person", "label": "Contact Person", "fieldtype": "Data"},
                {"fieldname": "phone", "label": "Phone", "fieldtype": "Data"},
                {"fieldname": "whatsapp", "label": "WhatsApp", "fieldtype": "Data"},
                {"fieldname": "email", "label": "Email", "fieldtype": "Data"},
                {"fieldname": "active_status", "label": "Active Status", "fieldtype": "Check", "default": "1"},
                {"fieldname": "notes", "label": "Notes", "fieldtype": "Small Text"}
            ],
            "permissions": [{"role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1}]
        })
        contractor.insert(ignore_permissions=True)
        print("Created Contractor")

    # Contract Request Recipient (Child Table)
    if not frappe.db.exists("DocType", "Contract Request Recipient"):
        contract_req_rec = frappe.get_doc({
            "doctype": "DocType",
            "name": "Contract Request Recipient",
            "module": "Applicant Processing",
            "custom": 0,
            "istable": 1,
            "fields": [
                {"fieldname": "contractor", "label": "Contractor", "fieldtype": "Link", "options": "Contractor", "in_list_view": 1},
                {"fieldname": "sent_date", "label": "Sent Date", "fieldtype": "Datetime", "in_list_view": 1},
                {"fieldname": "comm_method", "label": "Communication Method", "fieldtype": "Select", "options": "Email\nWhatsApp", "in_list_view": 1},
                {"fieldname": "response_status", "label": "Response Status", "fieldtype": "Select", "options": "Pending\nAccepted\nRejected", "default": "Pending", "in_list_view": 1}
            ]
        })
        contract_req_rec.insert(ignore_permissions=True)
        print("Created Contract Request Recipient")

    # Contract Request
    if not frappe.db.exists("DocType", "Contract Request"):
        contract_req = frappe.get_doc({
            "doctype": "DocType",
            "name": "Contract Request",
            "module": "Applicant Processing",
            "custom": 0,
            "naming_rule": "Expression",
            "autoname": "CR-.#####",
            "fields": [
                {"fieldname": "applicant", "label": "Applicant", "fieldtype": "Link", "options": "Applicant", "reqd": 1},
                {"fieldname": "cv_reference", "label": "CV Reference", "fieldtype": "Link", "options": "CV Record"},
                {"fieldname": "created_by", "label": "Created By", "fieldtype": "Link", "options": "User"},
                {"fieldname": "created_date", "label": "Created Date", "fieldtype": "Datetime"},
                {"fieldname": "status", "label": "Status", "fieldtype": "Select", "options": "Draft\nSent\nAccepted\nClosed", "default": "Draft"},
                {"fieldname": "recipients", "label": "Recipients", "fieldtype": "Table", "options": "Contract Request Recipient"}
            ],
            "permissions": [{"role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1}]
        })
        contract_req.insert(ignore_permissions=True)
        print("Created Contract Request")

    # Employee Task
    if not frappe.db.exists("DocType", "Employee Task"):
        employee_task = frappe.get_doc({
            "doctype": "DocType",
            "name": "Employee Task",
            "module": "Applicant Processing",
            "custom": 0,
            "naming_rule": "Expression",
            "autoname": "TASK-.#####",
            "fields": [
                {"fieldname": "applicant", "label": "Applicant", "fieldtype": "Link", "options": "Applicant", "reqd": 1},
                {"fieldname": "task_name", "label": "Task Name", "fieldtype": "Data", "reqd": 1},
                {"fieldname": "assigned_user", "label": "Assigned User", "fieldtype": "Link", "options": "User"},
                {"fieldname": "required", "label": "Required", "fieldtype": "Check", "default": "1"},
                {"fieldname": "status", "label": "Status", "fieldtype": "Select", "options": "Pending\nIn Progress\nCompleted", "default": "Pending"},
                {"fieldname": "completed_date", "label": "Completed Date", "fieldtype": "Datetime"}
            ],
            "permissions": [{"role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1}]
        })
        employee_task.insert(ignore_permissions=True)
        print("Created Employee Task")

    # Ticket
    if not frappe.db.exists("DocType", "Ticket"):
        ticket = frappe.get_doc({
            "doctype": "DocType",
            "name": "Ticket",
            "module": "Applicant Processing",
            "custom": 0,
            "naming_rule": "Expression",
            "autoname": "TKT-.#####",
            "fields": [
                {"fieldname": "applicant", "label": "Applicant", "fieldtype": "Link", "options": "Applicant", "reqd": 1},
                {"fieldname": "ticket_number", "label": "Ticket Number", "fieldtype": "Data", "reqd": 1},
                {"fieldname": "issue_date", "label": "Issue Date", "fieldtype": "Datetime"},
                {"fieldname": "departure_date", "label": "Departure Date", "fieldtype": "Datetime"},
                {"fieldname": "status", "label": "Status", "fieldtype": "Select", "options": "Booked\nDeparted\nCancelled", "default": "Booked"}
            ],
            "permissions": [{"role": "System Manager", "read": 1, "write": 1, "create": 1, "delete": 1}]
        })
        ticket.insert(ignore_permissions=True)
        print("Created Ticket")
        
    frappe.db.commit()

create_phase4_doctypes()
